export const GET_DATA_UNICORNS_REQUESTED = 'GET_DATA_UNICORNS_REQUESTED';
export const GET_DATA_UNICORNS_SUCCEEDED = 'GET_DATA_UNICORNS_SUCCEEDED';
export const GET_DATA_UNICORNS_FAILED = 'GET_DATA_UNICORNS_FAILED';

export const EDIT_DATA_UNICORNS_REQUESTED = 'EDIT_DATA_UNICORNS_REQUESTED';
export const EDIT_DATA_UNICORNS_SUCCEEDED = 'EDIT_DATA_UNICORNS_SUCCEEDED';
export const EDIT_DATA_UNICORNS_FAILED = 'EDIT_DATA_UNICORNS_FAILED';